apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: isaktivitetskrav
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 70
  startup:
    path: /internal/is_ready
    periodSeconds: 5
    timeout: 5
    failureThreshold: 30
  liveness:
    path: /internal/is_alive
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  readiness:
    path: /internal/is_ready
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  leaderElection: true
  prometheus:
    enabled: true
    path: /internal/metrics
  redis:
    - instance: isaktivitetskrav
      access: readwrite
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 384Mi
  ingresses:
    - "https://isaktivitetskrav.intern.nav.no"
  accessPolicy:
    inbound:
      rules:
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: prod-gcp
    outbound:
      external:
        - host: "login.microsoftonline.com"
        - host: "pdl-api.prod-fss-pub.nais.io"
        - host: "dokarkiv.prod-fss-pub.nais.io"
      rules:
        - application: syfo-tilgangskontroll
        - application: isaktivitetskravpdfgen
        - application: digdir-krr-proxy
          namespace: team-rocket
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: isaktivitetskrav-db
        diskAutoresize: true
  azure:
    application:
      allowAllUsers: true
      enabled: true
      claims:
        extra:
          - "NAVident"
  kafka:
    pool: nav-prod
  env:
    - name: KTOR_ENV
      value: "production"
    - name: SYFOTILGANGSKONTROLL_CLIENT_ID
      value: "prod-gcp.teamsykefravr.syfo-tilgangskontroll"
    - name: SYFOTILGANGSKONTROLL_URL
      value: "http://syfo-tilgangskontroll"
    - name: PDL_CLIENT_ID
      value: "prod-fss.pdl.pdl-api"
    - name: PDL_URL
      value: "https://pdl-api.prod-fss-pub.nais.io/graphql"
    - name: ARENA_CUTOFF
      value: "2023-03-10"
    - name: AUTOMATISK_OPPFYLT_CRONJOB_ENABLED
      value: "false"
    - name: NY_CRONJOB_ENABLED
      value: "false"
    - name: DOKARKIV_CLIENT_ID
      value: "prod-fss.teamdokumenthandtering.dokarkiv"
    - name: DOKARKIV_URL
      value: "https://dokarkiv.prod-fss-pub.nais.io"
    - name: KRR_CLIENT_ID
      value: "prod-gcp.team-rocket.digdir-krr-proxy"
    - name: KRR_URL
      value: "http://digdir-krr-proxy.team-rocket"
    - name: OUTDATED_AKTIVITETSKRAV_CUTOFF
      value: "2023-06-01"
    - name: OUTDATED_AKTIVITETSKRAV_CRONJOB_ENABLED
      value: "false"
