ALTER TABLE AKTIVITETSKRAV_VARSEL
    ADD COLUMN expired_varsel_published_at TIMESTAMPTZ NULL;

ALTER TABLE AKTIVITETSKRAV_VARSEL
    ADD COLUMN svarfrist TIMESTAMPTZ NOT NULL
        DEFAULT (SELECT created_at + INTERVAL '3 weeks'
                 FROM AKTIVITETSKRAV_VARSEL
                 LIMIT 1);