ALTER TABLE AKTIVITETSKRAV_VARSEL
    ADD COLUMN expired_varsel_published_at TIMESTAMPTZ DEFAULT NULL;

ALTER TABLE AKTIVITETSKRAV_VARSEL
    ADD COLUMN svarfrist DATE;

UPDATE AKTIVITETSKRAV_VARSEL
SET svarfrist = created_at + INTERVAL '3 weeks'
WHERE true;

ALTER TABLE AKTIVITETSKRAV_VARSEL
    ALTER COLUMN svarfrist SET NOT NULL
