name: kafka

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/kafka-aktivitetskrav.yaml'
      - '.nais/kafka/**'

jobs:
  deploy-kafka-aktivitetskrav-dev:
    name: Deploy Kafka topics to dev-gcp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy aktivitetskrav-vurdering topic to dev
        uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/kafka/aktivitetskrav.yaml
          VARS: .nais/kafka/dev.json

      - name: Deploy aktivitetskrav-varsel topic to dev
        uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/kafka/aktivitetskrav-varsel.yaml
          VARS: .nais/kafka/dev.json

      - name: Deploy aktivitetskrav-expired-varsel topic to dev
        uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/kafka/aktivitetskrav-expired-varsel.yaml
          VARS: .nais/kafka/dev.json

  deploy-kafka-aktivitetskrav-prod:
    name: Deploy Kafka topics to prod-gcp
    needs: deploy-kafka-aktivitetskrav-dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy aktivitetskrav-vurdering topic to prod
        uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .nais/kafka/aktivitetskrav.yaml
          VARS: .nais/kafka/prod.json

      - name: Deploy aktivitetskrav-varsel topic to prod
        uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .nais/kafka/aktivitetskrav-varsel.yaml
          VARS: .nais/kafka/prod.json

      - name: Deploy aktivitetskrav-expired-varsel topic to prod
        uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .nais/kafka/aktivitetskrav-expired-varsel.yaml
          VARS: .nais/kafka/prod.json
